<?php 

$encryption_set = array(
    'a' => array('!', 'a', '@'),
    'b' => array('#', 'c', 'd'),
    'c' => array('e', 'b', '$'),
    'd' => array('%', 'f', 'g'),
    'e' => array('h', 'i', '^'),
    'f' => array('&', 'j', '*'),
    'g' => array('(', 'k', 'l'),
    'h' => array('m', 'n', '-'),
    'i' => array('o', 'p', '_'),
    'j' => array('q', 'r', 's'),
    'k' => array('t', 'u', '+'),
    'l' => array('v', 'w', '/'),
    'm' => array('x', 'y', 'z'),
    'n' => array(':', 'A', 'B'),
    'o' => array('C', 'D', 'E'),
    'p' => array('F', 'G', 'H'),
    'q' => array('I', 'J', 'K'),
    'r' => array('L', 'M', 'N'),
    's' => array('O', 'P', 'Q'),
    't' => array('R', 'S', 'T'),
    'u' => array('U', 'V', 'W'),
    'v' => array('X', 'Y', 'Z'),
    'w' => array('1', '2', '3'),
    'x' => array('4', '5', '6'),
    'y' => array('7', '8', '9'),
    'z' => array('0', '?', '!')
);